config/routes.rb
Rails.application.routes.draw do

  resources :factories

  root 'factories#index'

end

app/models/factory.rb
class Factory < ActiveRecord::Base
	validates :name, :lower_limit, :upper_limit, :node_quantity, presence: true
	validates :lower_limit, :upper_limit, :node_quantity, numericality: { only_integer: true, greater_than: 0 }
	validates :node_quantity, numericality: { less_than_or_equal_to: 15 }
	validates :upper_limit, numericality: { greater_than: :lower_limit }

  def number
    random_list_counter = 0
    while random_list_counter < node_quantity
      random_number = rand(lower_limit..upper_limit)
      random_list.push(random_number)
      random_list_counter += 1
    end
    return random_list
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  before_action :set_factory, only: [:show, :edit, :update, :destroy]

  def index
    @factories = Factory.all
  end

  def show
  end

  def new
    @factory = Factory.new
  end

  def edit
  end

  def create
    @factory = Factory.new(factory_params)

    respond_to do |format|
      if @factory.save
        format.html { redirect_to @factory, notice: 'Factory was successfully created.' }
        format.json { render :show, status: :created, location: @factory }
      else
        format.html { render :new }
        format.json { render json: @factory.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @factory.update(factory_params)
        format.html { redirect_to @factory, notice: 'Factory was successfully updated.' }
        format.json { render :show, status: :ok, location: @factory }
      else
        format.html { render :edit }
        format.json { render json: @factory.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @factory.destroy
    respond_to do |format|
      format.html { redirect_to factories_url, notice: 'Factory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_factory
      @factory = Factory.find(params[:id])
    end

    def factory_params
      params.require(:factory).permit(:name, :lower_limit, :upper_limit, :node_quantity, :random_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/views/factories/_form.html.erb
<%= form_for(@factory) do |f| %>
  <% if @factory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factory.errors.count, "error") %> prohibited this factory from being saved:</h2>

      <ul>
      <% @factory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lower_limit %><br>
    <%= f.number_field :lower_limit %>
  </div>
  <div class="field">
    <%= f.label :upper_limit %><br>
    <%= f.number_field :upper_limit %>
  </div>
  <div class="field">
    <%= f.label :node_quantity %><br>
    <%= f.number_field :node_quantity %>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factories/edit.html.erb
<h1>Editing Factory</h1>

<%= render 'form' %>

<%= link_to 'Show', @factory %> |
<%= link_to 'Back', factories_path %>

app/views/factories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Random Trees</h1>

<%= link_to 'New Factory', new_factory_path %>
<body>
<div class="container">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Lower</th>
        <th>Upper</th>
        <th>Quantity</th>
        <th>Random Numbers</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @factories.each do |factory| %>
        <tr>
          <td><%= factory.name %></td>
          <td><%= factory.lower_limit %></td>
          <td><%= factory.upper_limit %></td>
          <td><%= factory.node_quantity %></td>
          <td><%= factory.number.join(", ").html_safe %></td>
          <td><%= link_to 'Show', factory %></td>
          <td><%= link_to 'Edit', edit_factory_path(factory) %></td>
          <td><%= link_to 'Destroy', factory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>
</div>
</body>

app/views/factories/new.html.erb
<h1>New Factory</h1>

<%= render 'form' %>

<%= link_to 'Back', factories_path %>

app/views/factories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @factory.name %>
</p>

<p>
  <strong>Lower:</strong>
  <%= @factory.lower_limit %>
</p>

<p>
  <strong>Upper:</strong>
  <%= @factory.upper_limit %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @factory.node_quantity %>
</p>

<%= link_to 'Edit', edit_factory_path(@factory) %> |
<%= link_to 'Back', factories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Nodetree</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/style.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script src="../../assets/javascripts/tree.js.erb"></script>
  </body>
</html>